apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sunk.fullname" . }}-openldap-ldif
  labels:
    {{- include "sunk.labels" . | nindent 4 }}
data:
  bootstrap.ldif: |
    dn: ou=users,{{ .Values.openldap.rootDN }}
    objectClass: organizationalUnit
    ou: users

    dn: ou=groups,{{ .Values.openldap.rootDN }}
    objectClass: organizationalUnit
    ou: groups

    {{- range .Values.openldap.groups }}

    dn: cn={{ .name }},ou=groups,{{ $.Values.openldap.rootDN }}
    objectClass: posixGroup
    cn: {{ .name }}
    gidNumber: {{ .gid }}
    {{- range .members }}
    memberUid: {{ . }}
    {{- end }}
    {{- end }}

    {{- range .Values.openldap.users }}

    dn: cn={{ .username }},ou=groups,{{ $.Values.openldap.rootDN }}
    objectClass: posixGroup
    cn: {{ .username }}
    gidNumber: {{ .gid }}

    dn: uid={{ .username }},ou=users,{{ $.Values.openldap.rootDN }}
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    {{- if .sshPublicKey }}
    objectClass: ldapPublicKey
    sshPublicKey: {{ .sshPublicKey }}
    {{- end }}
    uid: {{ .username }}
    sn: {{ .username }}
    cn: {{ .username }}
    uidNumber: {{ .uid }}
    gidNumber: {{ .gid }}
    homeDirectory: /home/{{ .username }}
    loginShell: /bin/bash
    userPassword: {{ .password }}
    {{- end }}
