apiVersion: slinky.slurm.net/v1beta1
kind: Controller
metadata:
  name: {{ include "sunk.fullname" . }}
  labels:
    {{- include "sunk.labels" . | nindent 4 }}
spec:
  clusterName: {{ .Values.slurm.clusterName }}
  {{- if .Values.slurm.accounting.enabled }}
  accountingRef:
    name: {{ include "sunk.fullname" . }}
  {{- end }}
  {{- if .Values.slurm.config }}
  configFileRefs:
    - name: {{ include "sunk.fullname" . }}-config
  {{- end }}
  slurmKeyRef:
    name: {{ include "sunk.fullname" . }}-slurm-key
    key: slurm.key
  jwtKeyRef:
    name: {{ include "sunk.fullname" . }}-jwt-key
    key: jwt.key
  slurmctld:
    image: "{{ .Values.slurm.controller.slurmctld.image.repository }}:{{ .Values.slurm.controller.slurmctld.image.tag }}"
    imagePullPolicy: IfNotPresent
  reconfigure:
    image: "{{ .Values.slurm.controller.reconfigure.image.repository }}:{{ .Values.slurm.controller.reconfigure.image.tag }}"
    imagePullPolicy: IfNotPresent
  logfile:
    image: docker.io/library/alpine:latest
    imagePullPolicy: IfNotPresent
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.slurm.controller.persistence.size }}
