{{- $slurmSecretName := printf "%s-slurm-key" (include "sunk.fullname" .) -}}
{{- $slurmSecret := lookup "v1" "Secret" .Release.Namespace $slurmSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $slurmSecretName }}
  labels:
    {{- include "sunk.labels" . | nindent 4 }}
type: Opaque
immutable: true
data:
  {{- if $slurmSecret }}
  slurm.key: {{ index $slurmSecret.data "slurm.key" }}
  {{- else }}
  slurm.key: {{ randAscii 1024 | b64enc }}
  {{- end }}
---
{{- $jwtSecretName := printf "%s-jwt-key" (include "sunk.fullname" .) -}}
{{- $jwtSecret := lookup "v1" "Secret" .Release.Namespace $jwtSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $jwtSecretName }}
  labels:
    {{- include "sunk.labels" . | nindent 4 }}
type: Opaque
immutable: true
data:
  {{- if $jwtSecret }}
  jwt.key: {{ index $jwtSecret.data "jwt.key" }}
  {{- else }}
  jwt.key: {{ genPrivateKey "rsa" | b64enc }}
  {{- end }}
---
{{- $mariadbPassName := "mariadb-password" -}}
{{- $mariadbPass := lookup "v1" "Secret" .Release.Namespace $mariadbPassName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $mariadbPassName }}
  labels:
    {{- include "sunk.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $mariadbPass }}
  password: {{ index $mariadbPass.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
