{{- range $key, $loginset := .Values.slurm.loginsets }}
{{- if $loginset.enabled }}
---
apiVersion: slinky.slurm.net/v1beta1
kind: LoginSet
metadata:
  name: {{ include "sunk.fullname" $ }}-{{ $key }}
  labels:
    {{- include "sunk.labels" $ | nindent 4 }}
spec:
  controllerRef:
    name: {{ include "sunk.fullname" $ }}
  sssdConfRef:
    name: {{ include "sunk.fullname" $ }}-sssd
    key: sssd.conf
  extraSshdConfig: |
    PasswordAuthentication yes
    KbdInteractiveAuthentication yes
  replicas: {{ $loginset.replicas | default 1 }}
  template:
    spec:
      terminationGracePeriodSeconds: 7200
  login:
    image: "{{ $loginset.login.image.repository }}:{{ $loginset.login.image.tag }}"
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
            - bash
            - -c
            - |
              while pgrep -x sshd-session > /dev/null; do
                sleep 5
              done
  initconf:
    image: docker.io/library/alpine:latest
    imagePullPolicy: IfNotPresent
  service:
    spec:
      type: {{ $loginset.serviceType | default "ClusterIP" }}
{{- end }}
{{- end }}
